# Generated by Django 5.2 on 2026-09-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_telegramlink_phoneconfirmationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_coffee_cups',
            field=models.PositiveIntegerField(default=0, help_text='Заработанные, но ещё не выданные бесплатные чашки (после накопления coffee_cups).'),
        ),
    ]
