# Generated by Django 5.2 on 2026-09-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_add_translation_and_bonus_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='bonus_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
