# Generated by Django 5.2 on 2026-09-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_bonus_awarded_order_bonus_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
