# Generated by Django 5.2 on 2026-09-24 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0007_order_bonus_awarded_order_bonus_earned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Положительное значение — начисление, отрицательное — списание.')),
                ('reason', models.CharField(choices=[('order_earned', 'Начислено за заказ'), ('order_spent', 'Списано на заказ'), ('order_refunded', 'Возврат баллов за отменённый заказ'), ('admin_adjustment', 'Корректировка администратором')], max_length=20)),
                ('balance_after', models.IntegerField(help_text='Баланс пользователя сразу после этой операции.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Кто инициировал операцию (курьер/админ). Пусто для автоматических начислений.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='bonus_loyal_user_id_d39f61_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order', 'reason'), name='bonus_one_ledger_entry_per_order_reason')],
            },
        ),
    ]
